### ISSUE TITLE
Mobile menu and breadcrumb broken

### ISSUE THREAD

**Issue by cenobitz** [redchamps/snowdog-menu-luma-support#1]
Hi.

For now this plugin breakes breadcrumb (not showing categories) for products.
It is also not working properly on mobile devices - when You click expand button on mobile it expand it and redirect to URL. 
Tested on fresh installs Magento wer. 2.3.5-p1, mobile chrome and firefox.

After disabling module all issues fixed.

C.

**Comment by redchamps** [comment]
@cenobitz Thanks for reporting.

The breadcrumb issue is due to original repo https://github.com/SnowdogApps/magento2-menu please report it there.

Will check the mobile menu issue soon & get back to you

**Comment by redchamps** [comment]
The mobile menu is working fine for us. You can see it here http://235p1.test.redchamps.com/ (it's clean installation of 2.3.5-p1)

**Comment by cenobitz** [comment]
You misunderstand me. As I mentioned mobile menu is not working on submenu items. When You click expand it both expands and redirects to category which is not expected behaviour because you got less than 1 second to see submenu items :) on test server You have only menu without submenu items and I can confirm that this works fine.

**Comment by cenobitz** [comment]
And as You can see http://235p1.test.redchamps.com/category-5/simple-product-118.html
it is breaking breadcrumbs. It never shows exact and expected path. Disable plugin and everything start working as expected.

**Comment by redchamps** [comment]
> You misunderstand me. As I mentioned mobile menu is not working on submenu items. When You click expand it both expands and redirects to category which is not expected behaviour because you got less than 1 second to see submenu items :) on test server You have only menu without submenu items and I can confirm that this works fine.

Yes, the problem  is visible now at http://235p1.test.redchamps.com/. thanks for explaining. We will fix it soon or you can put up a pull request for fix & we can merge it.

**Comment by redchamps** [comment]
> And as You can see http://235p1.test.redchamps.com/category-5/simple-product-118.html
> it is breaking breadcrumbs. It never shows exact and expected path. Disable plugin and everything start working as expected.

Yes, we can repeat it. But this extension is addon for extension https://github.com/SnowdogApps/magento2-menu for adding support for luma theme in terms of appearance.

The breadcrumb problem should be in original extension, not in this addon as it touches only the appearance.

**Comment by cenobitz** [comment]
thanks for clarifying. So there are two bugs in snowdog luma menu. I reported it there You can close issue here as it is not stricly related. Regards, C

**Comment by redchamps** [comment]
The mobile menu problem is in this extension but the breadcrumb problem is in snowdog luma menu. We can leave this issue open till the time we fix mobile menu.

**Comment by web5exposure** [comment]
Are there any updates about the mobile menu issue?

**Comment by template-provider** [comment]
+1 ... I would like to help, but cannot identify the exact location for this issue
@redchamps can you help us here plz

**Comment by template-provider** [comment]
it seems that the css class "level-top" is missing for the "li" element.
currently it is only at the "a" element of a menu.
by adding the level-top to the menu.phtml it works
```
                /** appending the level0 class to root navigation element */
                $itemClasses = ' level0 level-top' . $parentClass . $additionalClasses;
```
But I am not sure about the logic of a sub sub menu.... maybe somebody can check it out?

**Comment by redchamps** [comment]
Hi @template-provider 

Thanks for looking into it.

Unfortunately, we are occupied with some priority work at the moment & it may take us few weeks to close this issue.

If you may check this further  & submit a pull request then that will be very helpful. In case not, then we will try to fix it as soon as possible.

Thanks again.

**Comment by vseager** [comment]
+1 Is there an update for the mobile sub menu support?

**Comment by redchamps** [comment]
Hi All,

We are archiving this repository in favour of module created by @vseager https://github.com/vseager/magento2-snowdog-menu-luma 

Please switch to the module from @vseager
